travis:
  secure:
    BINSTAR_TOKEN: YOxxFGLiUrrnFZecmr32LFyTfBqitj8ceZliriANUPO9pBKiIci9IBdKPYhHXeOv7GeUT7jTvlDC3lcqAnV7Y9ik6neRYaAZA8Ou3rrS1NW9u++NJ/82SDLaPPKoSOyI9eSZsqIiu9e6Rd7mkBh5Qp7Uu4TnTvFLCIoBbglA1SWR5XO9GQgquGG9eTDnoDflseqd4i0yaB7YEyRGgFlwLzVI6NY4YpuxZHiCwHy1hI75ZtBoaFfmjIxCRVvWWyWdD21E/ZVceYB5Xbwl8YRt3TRJI1i/ElPHX8kvcgf4gYQsd39S439U+kycwuxl1U6wZmqCQ1xQ+3CubjMWTP4k14dr1fDVEVzwJ3G4wQ3ei32T5g5dpaSIhhU+DVjM0nmerg4anndJKX718l8jWADkqFmEEfjyfDTzgjL9PdG+lJORt4finbrTETBD5jz7slufKVWzv8njodd3dSuQIYqcJcr3/z8QFcPBs3gIQghvpitsgQ9rRbmNMpZRnPrqxfz0vSlKpxBLbZKntl1fVs0arucL9Yzp4R1/XZZZLoMy+CYGXxQs9CEzMXku/Qh/7dmzRBJHcXqCTOa5lQVLke1ylp5LROvV4DFocrKXcuvCozDm3uwoX26pj2mGVpHrc8ZCUsaX1qGk9mab4lcUX6TmujzZ1G6pjvonXJqwnipfjr0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
