travis:
  secure:
    BINSTAR_TOKEN: FijnVTVBhNDVJNE00Tiu2PFxR2n1VG5/MLXcEbFpUukeIrtxxaUqVLGvM+G1dlGm+XX1emfejbMpx485jEmA0kisLGwYDCbSkk2l35Bn1U0gFGp6Ismt43LS9Wga0z33jHfo0uT1mF8/DhxgBnob9ChYJkovLmov2zhaIWL7uV1e76oajtJSf3mAEi5iXDe0ga8uJFfbg7u9KZ1QfEZX7VwQKxSp9YuzJsZSKbmn+QIwbYf8N82cMmqZgpG2wwZ195ZHCKv61QpfkUKHIq4jwVl9SYLGglWwlOHZw1Ur+gpua1M7jqukNEqwp2bWES8IcbhOFyxb6OZ5Z/+qbu5F3kjSmmiGHLVB9SQKmKLHuZ/1iYG8JR8QEkhKKlSeAxKYmVh5xQbNNfMJQNKns02lMIaQatcdK1sAuwY2bLKyCJJK3KfxpAAYA1MZvhjRybC4K1XzK3BnF21P74B43hzt7rWfWro2HN6F9w/gZ/FJElLjcsf5zdY9upbUnibknoqXfjyMw5BsDyr0eeZxPC12IiJl9LsyE//TAxRtZv5FEGRZVj7JutJDiT20mymXXb71rEMQpazoNqCyt1jIWhsJLzUB+9Agt1AJn4jzR2G/0EjAUVdteuz/yqgGU3YOt06fmDjF6ErK+a+erkoWj3+yhNXtzc8kijcwZ9Y++AgTB/E=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
